WIP: iss30 almost done
- Most methods/code that can be moved out of main_window have been
- There are two errors that I still need to clean up:
1. AttributeError: 'SystrayIcon' object has no attribute 'showMessage'
  When trying to close the main window with the x button, it doesn't
  minimize or quit.
2. Dashboard email/password don't show in the main window. This was
caused by moving all of that code to the main_window_ui.py, but I'd like
to keep it there