Support on ubuntu 16.04. Closes #36.
Ubuntu 16.04 - Success
Ubuntu 18.04 - Failure
ImportError: /usr/lib/x86_64-linux-gnu/libGL.so.1: undefined symbol:
_glapi_tls_Current
[15048] Failed to execute script merlink

Mint 18.3 - Failure
The VPN connection 'vpn-l2tp' failed because the VPN service failed to
start