Test #19 - testing with qt5-default
This is the error we get when downloading and installing:

Error: PyQt5 requires Qt v5.0 or later. You seem to be using v4.8.6. Use
the --qmake flag to specify the correct version of qmake.

The solution
[here](https://askubuntu.com/questions/609238/error-pyqt5-requires-qt-v5-0-or-later)
is to install qt5-default